org: shrestharajat
app: demopy
service: aws-python-http-api-project
frameworkVersion: '3'

plugins:
  - serverless-domain-manager
 
custom:
  customDomain:
    domainName: 'api.shrestharajat.com'
    basePath: ''
    stage: '$default'
    createRoute53Record: true

provider:
  name: aws
  runtime: python3.8
  apiGateway:
    apiKeys:
      - name: 'rajat'
      - value: 'XIUas1SNUIOAPDIJdsaN34sdJIOSJUDDS' 

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: post
          private: true