

org: shrestharajat
app: demopy
service: aws-python-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  memorySize: 2000
  timeout: 900
  architecture: x86_64
  stackTags:
    product: poc
    env: test
    created-date: 2023-02-10
    team: data
  apiGateway:
    apiKeys:
      - name: 'rajat'
      - value: 'XIUas1SNUIOAPDIJdsaN34sdJIOSJUDDS' 

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: post
          private: true